// Generates the home-screen icon as a PNG and writes it to src/icon-data.ts.
//
// Why generate rather than commit a binary: the icon is four flat shapes on a
// background, and a 40-line generator is easier to review, recolour, and diff
// than an opaque blob. Run `npm run make-icon` after changing it.
//
// Why a PNG at all, when the page is styled entirely in CSS: iOS ignores SVG
// for `apple-touch-icon`, and without one, Add to Home Screen uses a screenshot
// of the page as the icon. A screenshot is what makes an installed page feel
// like a bookmark instead of a tool.
//
// No dependencies -- zlib is built into node, and the PNG container is a
// signature plus three chunks.

import { deflateSync } from "node:zlib";
import { writeFileSync } from "node:fs";

const SIZE = 512;
const BG = [0x0b, 0x0e, 0x13]; // --bg from the page, so the icon matches it
const TEAL = [0x2d, 0xd4, 0xbf]; // --ac
const BLUE = [0x7c, 0x9c, 0xf5]; // --ac2
const DIM = [0x3a, 0x44, 0x52];

// --- CRC32 (implemented rather than imported: node's zlib.crc32 is recent) ---
const CRC_TABLE = new Int32Array(256);
for (let n = 0; n < 256; n++) {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  CRC_TABLE[n] = c;
}
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

// --- draw ------------------------------------------------------------------
// RGBA, straight alpha. Everything is opaque; the rounded corners are painted
// in the background colour rather than cut out, because iOS masks the icon to
// its own shape anyway and a transparent corner would show through as black.
const px = Buffer.alloc(SIZE * SIZE * 4);
const set = (x, y, [r, g, b]) => {
  if (x < 0 || y < 0 || x >= SIZE || y >= SIZE) return;
  const i = (y * SIZE + x) * 4;
  px[i] = r; px[i + 1] = g; px[i + 2] = b; px[i + 3] = 255;
};

for (let y = 0; y < SIZE; y++) for (let x = 0; x < SIZE; x++) set(x, y, BG);

// Four stacked bars of decreasing width: a decision log, newest on top. The top
// two are accent-coloured (active), the rest dimmed (superseded) -- the same
// idea the page itself is built around.
const bars = [
  { w: 0.62, c: TEAL },
  { w: 0.50, c: BLUE },
  { w: 0.38, c: DIM },
  { w: 0.26, c: DIM },
];
const barH = Math.round(SIZE * 0.088);
const gap = Math.round(SIZE * 0.052);
const left = Math.round(SIZE * 0.19);
const radius = Math.round(barH / 2);
let top = Math.round((SIZE - (bars.length * barH + (bars.length - 1) * gap)) / 2);

for (const bar of bars) {
  const w = Math.round(SIZE * bar.w);
  for (let y = 0; y < barH; y++) {
    for (let x = 0; x < w; x++) {
      // Rounded caps: skip pixels outside the end circles.
      const dxL = radius - x;
      const dxR = x - (w - radius - 1);
      const dy = y - (barH - 1) / 2;
      if (dxL > 0 && dxL * dxL + dy * dy > radius * radius) continue;
      if (dxR > 0 && dxR * dxR + dy * dy > radius * radius) continue;
      set(left + x, top + y, bar.c);
    }
  }
  top += barH + gap;
}

// --- encode ----------------------------------------------------------------
const raw = Buffer.alloc(SIZE * (SIZE * 4 + 1));
for (let y = 0; y < SIZE; y++) {
  raw[y * (SIZE * 4 + 1)] = 0; // filter type 0 (None)
  px.copy(raw, y * (SIZE * 4 + 1) + 1, y * SIZE * 4, (y + 1) * SIZE * 4);
}
const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(SIZE, 0);
ihdr.writeUInt32BE(SIZE, 4);
ihdr[8] = 8;  // bit depth
ihdr[9] = 6;  // colour type: RGBA
const png = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  chunk("IHDR", ihdr),
  chunk("IDAT", deflateSync(raw, { level: 9 })),
  chunk("IEND", Buffer.alloc(0)),
]);

const b64 = png.toString("base64");
writeFileSync(
  new URL("../src/icon-data.ts", import.meta.url),
  `// GENERATED by scripts/make-icon.mjs -- do not edit by hand.\n` +
    `// Run \`npm run make-icon\` to regenerate after changing the generator.\n` +
    `// ${SIZE}x${SIZE} PNG, ${png.length} bytes.\n` +
    `export const ICON_PNG_BASE64 =\n  "${b64}";\n`,
);
console.log(`wrote src/icon-data.ts (${SIZE}x${SIZE}, ${png.length} bytes PNG)`);
